<?php

$stockQty = $this->getProduct()->getExtensionAttributes()->getStockItem()->getQty();
$inStock = $this->getProduct()->getExtensionAttributes()->getStockItem()->getIsInStock();

if (!$inStock) {
  $leadtime = 11;
} elseif ($stockQty>=1) {
  $leadtime = 10;
} else {
  $leadtime = $this->getProduct()->getAttributeText('source_leadtime');
}

switch($leadtime) {
  case 0:
     $lead_text = "Kontakta oss för leveranstid";
     break;
  case 10:
     $lead_text = "Finns i lager";
     break;
  case 11:
     $lead_text = "Utgått";
     $leadtime = 5;
     break;
  case 1:
     $lead_text = "1-3 dagar";
     break;
  case 2:
     $lead_text = "4-7 dagar";
     break;
  case 3:
     $lead_text = "1-2 veckor";
     break;
  case 4:
     $lead_text = "3-4 veckor";
     break;
  default:
     $lead_text = "Osäker leveranstid";
     $leadtime = 5;
     break;
}
?>
<div class="product-info-leadtime">
  <div id="leadtime-wrapper" class=<?= "leadtime-".$leadtime ?>>
    <div class="leadtime-truck" style="float: left;">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
        <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
      </svg>
    </div>
    <div class="leadtime-text" style="padding-top: 7px; margin-left:40px">
      <span id="leadtime"><?= $lead_text ?></span>
    </div>
  </div>
</div>
